services:
  api:
    container_name: riga-weather
    build:
      context: ..
      dockerfile: docker/Dockerfile
    networks:
      - riga_weather
      - proxy
    restart: unless-stopped
    env_file: ../.env

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: "redis_riga_weather"
    networks:
      - riga_weather

networks:
  riga_weather:
  proxy:
    external: true
